# Generated by Django 4.2.5 on 2023-09-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summoner_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sumooner',
            new_name='Summoner',
        ),
    ]
