# Generated by Django 4.2.5 on 2023-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner_search', '0002_rename_sumooner_summoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='summonerLevel',
            field=models.IntegerField(default=0),
        ),
    ]
