# Generated by Django 4.2.6 on 2024-02-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('scam_detail', models.TextField()),
                ('report_count', models.IntegerField(default=0)),
            ],
        ),
    ]
