# Generated by Django 4.2.6 on 2024-02-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='discord_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
