# Generated by Django 4.2.6 on 2024-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_userreport_discord_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userreport',
            name='scam_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='tags',
            field=models.ManyToManyField(related_name='user_reports', to='reports.tag'),
        ),
    ]
