# Generated by Django 4.2.6 on 2024-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_tag_alter_userreport_scam_detail_userreport_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='data_value',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
