# Generated by Django 4.2.6 on 2024-02-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_tag_data_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='data_value',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
