# Generated by Django 4.2.6 on 2024-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_scamrecord_report_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='scam_detail',
        ),
    ]
