# Generated by Django 4.2.6 on 2024-02-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_userreport_scam_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scamrecord',
            name='nickname',
        ),
        migrations.AddField(
            model_name='scamrecord',
            name='user_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scam_records', to='reports.userreport'),
        ),
    ]
